#!/bin/bash
#PBS -N synthetic
#PBS -A GT-awu36
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=4gb
#PBS -j oe
#PBS -o out/synthetic.out
#PBS -t 8,15,16,17,18,19,20,21

cd $PBS_O_WORKDIR # change to directory from where I submit job
module load anaconda3/2021.05
conda activate cli726

params=`sed -n "${PBS_ARRAYID} p" synthetic1.input`
paramsArray=($params)
a=${paramsArray[0]}
b=${paramsArray[1]}
c=${paramsArray[2]}

python synthetic.py $a $b $c
echo "Started on `/bin/hostname`"